import { MobileVehicleCategory } from '../types';

export const MOBILE_FLEET: MobileVehicleCategory[] = [
  {
    id: '2w',
    name: '2-Wheeler (Bike)',
    badge: 'Fastest',
    capacityKg: 20,
    dimensions: '40cm x 40cm',
    baseFare: 45,
    baseKm: 2,
    ratePerKm: 8.5,
    etaMinutes: 3,
    icon: '🛵',
    description: 'Instant pickup for documents, parcels & food boxes.',
    popularFor: 'Small Parcels & Documents',
  },
  {
    id: '3w',
    name: '3-Wheeler (Tempo)',
    badge: 'Popular',
    capacityKg: 500,
    dimensions: '5.5ft x 4ft',
    baseFare: 160,
    baseKm: 2,
    ratePerKm: 15.0,
    etaMinutes: 4,
    icon: '🛺',
    description: 'Small shop inventory, retail crates, and cartons.',
    popularFor: 'Retail Cartons & Appliances',
  },
  {
    id: '3w-ev',
    name: '3-Wheeler Electric',
    badge: '🌱 Eco Saver',
    capacityKg: 500,
    dimensions: '5.5ft x 4.5ft',
    baseFare: 150,
    baseKm: 2,
    ratePerKm: 13.5,
    etaMinutes: 5,
    icon: '⚡',
    description: 'Zero emission city deliveries at reduced cost.',
    popularFor: 'Green FMCG City Logistics',
  },
  {
    id: 'tata-ace',
    name: 'Tata Ace (Chota Hathi)',
    badge: '⭐ Most Popular',
    capacityKg: 750,
    dimensions: '7ft x 4.5ft',
    baseFare: 230,
    baseKm: 2,
    ratePerKm: 19.0,
    etaMinutes: 4,
    icon: '🚛',
    description: 'The standard for furniture, house moving & wholesale goods.',
    popularFor: '1-BHK Moving, Plywood, Hardware',
  },
  {
    id: 'pickup-8ft',
    name: 'Pickup 8ft (Bolero)',
    badge: 'Heavy Duty',
    capacityKg: 1200,
    dimensions: '8ft x 4.5ft',
    baseFare: 320,
    baseKm: 2,
    ratePerKm: 23.0,
    etaMinutes: 6,
    icon: '🛻',
    description: 'Construction material, pipes, steel, and heavy cargo.',
    popularFor: 'Steel, Heavy Machinery, 2-BHK',
  },
  {
    id: 'tata-407',
    name: 'Tata 407 (10ft)',
    badge: 'Industrial',
    capacityKg: 2500,
    dimensions: '9.5ft x 5.5ft',
    baseFare: 550,
    baseKm: 3,
    ratePerKm: 32.0,
    etaMinutes: 8,
    icon: '🚚',
    description: 'Factory equipment, warehouse logistics & full office shifting.',
    popularFor: 'Factory Logistics, Full Office',
  },
  {
    id: 'container-14ft',
    name: '14ft / 19ft Container',
    badge: 'Interstate',
    capacityKg: 5000,
    dimensions: '14ft x 6ft',
    baseFare: 1200,
    baseKm: 5,
    ratePerKm: 42.0,
    etaMinutes: 15,
    icon: '🚛',
    description: 'Covered container for intercity cargo and heavy distribution.',
    popularFor: 'Interstate Cargo & FMCG',
  },
];
